<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.11">
  <POU Name="WConcat2x" Id="{9861941e-073b-42f5-9fd2-e9090765bc44}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION WConcat2x : WSTRING(255)
VAR_INPUT
	wsExpression1: WSTRING(255);
	wsExpression2: WSTRING(255);
END_VAR

]]></Declaration>
    <Implementation>
      <ST><![CDATA[WConcat2x := WCONCAT(wsExpression1, wsExpression2);]]></ST>
    </Implementation>
    <LineIds Name="WConcat2x">
      <LineId Id="19" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>