<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4020.12">
  <POU Name="F_TargetReachedOrLower" Id="{4cd65146-0c1a-48df-a4a3-8832351a5c41}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION F_TargetReachedOrLower : BOOL
VAR_INPUT
	fCurrentPos: LREAL;
	fTargetPos: LREAL;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[
F_TargetReachedOrLower := fCurrentPos <= (fTargetPos + fEpsilon);
]]></ST>
    </Implementation>
    <LineIds Name="F_TargetReachedOrLower">
      <LineId Id="3" Count="1" />
      <LineId Id="2" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>