<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4020.12">
  <POU Name="F_TargetReachedOrHigher" Id="{00ddc253-e675-4b1f-98a1-5439eb7a1734}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION F_TargetReachedOrHigher : BOOL
VAR_INPUT
	fCurrentPos: LREAL;
	fTargetPos: LREAL;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[
F_TargetReachedOrHigher := fCurrentPos >= (fTargetPos - fEpsilon);
]]></ST>
    </Implementation>
    <LineIds Name="F_TargetReachedOrHigher">
      <LineId Id="3" Count="1" />
      <LineId Id="2" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>