<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4020.12">
  <POU Name="F_TargetWindowReachedAxisRef" Id="{61062702-2c06-46f5-a7ac-a9c37e4bd3ab}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION F_TargetWindowReachedAxisRef : BOOL
VAR_IN_OUT
	/// Achse als Referenz
	fbAxis		:FB_AxisDriver;
END_VAR
VAR_INPUT
	fTargetPos: LREAL;
	fWindow: LREAL;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[
F_TargetWindowReachedAxisRef := fbAxis.Position >= (fTargetPos - fWindow) AND fbAxis.Position <= (fTargetPos + fWindow);
]]></ST>
    </Implementation>
    <LineIds Name="F_TargetWindowReachedAxisRef">
      <LineId Id="3" Count="1" />
      <LineId Id="2" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>