<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4020.12">
  <POU Name="F_TargetWindowReached" Id="{a1d9bfbe-a94d-4f6b-92e3-d1d03203f03c}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION F_TargetWindowReached : BOOL
VAR_INPUT
	fCurrentPos: LREAL;
	fTargetPos: LREAL;
	fWindow: LREAL;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[
F_TargetWindowReached := fCurrentPos >= (fTargetPos - fWindow) AND fCurrentPos <= (fTargetPos + fWindow);
]]></ST>
    </Implementation>
    <LineIds Name="F_TargetWindowReached">
      <LineId Id="3" Count="1" />
      <LineId Id="2" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>